### ISSUE TITLE
Sebia HELP

### ISSUE THREAD

**Issue by HackProB1** [SSebia/GTOS_leak#4]
i need this things:
#include "stdafx.h"
#include <cctype>
#include <cstdio>
#include <cstring>
#include <ctime>
#include <fstream>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <locale>
#include <mysql.h>
#include <sstream>
#include <sstream>
#include <string>
#include <time.h>
#include <vector>
#include "json.hpp"
#include "enet/enet.h"

**Comment by HackProB1** [comment]
#include "stdafx.h"
#include <cctype>
#include <cstdio>
#include <cstring>
#include <ctime>
#include <fstream>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <locale>
#include <mysql.h>
#include <sstream>
#include <sstream>
#include <string>
#include <time.h>
#include <vector>
#include "json.hpp"
#include "enet/enet.h"

**Comment by SSebia** [comment]
Just link them into your project, too lazy to help.
