### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by bexpg000** [SSebia/GTOS_leak#8]
dont waste ur time to build this sh1t

**Comment by SSebia** [comment]
How I'm supposed to know why u are crashing, maybe items.dat issue probably.

**Comment by bexpg000** [comment]
> How I'm supposed to know why u are crashing, maybe items.dat issue probably.



> How I'm supposed to know why u are crashing, maybe items.dat issue probably.

i updated items.dat

**Comment by bexpg000** [comment]
> How I'm supposed to know why u are crashing, maybe items.dat issue probably.

dm me in discord
