### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by bexpg000** [SSebia/GTOS_leak#9]
![image](https://user-images.githubusercontent.com/74148875/101014620-33b7dc80-3577-11eb-8c27-96633ed31a32.png)

crashing after loading item descriptions

**Comment by SSebia** [comment]
It is possible because you are missing descriptions.txt or u have made some shit In it, and idk ur items.dat code changed as i can see so yea.

**Comment by SSebia** [comment]
Just debug it and see where it fails.

**Comment by bexpg000** [comment]
i dont missing anything ???!

**Comment by bexpg000** [comment]
> Just debug it and see where it fails.

code not full

**Comment by bexpg000** [comment]
whatever i try way to fix mysql also json gtos here if anyone need use it https://github.com/bexpg000/gtos-gtps/ [no error]

**Comment by bexpg000** [comment]
whatever i find way to fix mysql also json gtos here if anyone need can it https://github.com/bexpg000/gtos-gtps/ [no error]

**Comment by bexpg000** [comment]
whatever i find way to fix mysql also json gtos here https://github.com/bexpg000/gtos-gtps/ [no error]
